/*
1. base de datos
*/

CREATE TABLE CARRO(
IDCARRO INT NOT NULL IDENTITY(1,1),
PLACA VARCHAR(6) NOT NULL,
MARCA VARCHAR(50) NOT NULL,
MODELO VARCHAR(50) NOT NULL,
COSTO MONEY NOT NULL,
DISPONIBLE BIT NOT NULL,
CONSTRAINT PK_IDCARRO PRIMARY KEY(IDCARRO)
);

CREATE TABLE CLIENTE(
IDCLIENTE INT NOT NULL IDENTITY(1,1),
CEDULA VARCHAR(20) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
TELEFONO1 VARCHAR(12) NOT NULL,
TELEFONO2 VARCHAR(12) NOT NULL,
CONSTRAINT PK_IDCLIENTE PRIMARY  KEY(IDCLIENTE)
);

CREATE TABLE ALQUILER(
IDALQUILER INT NOT NULL IDENTITY(1,1),
IDCLIENTE INT NOT NULL,
IDCARRO INT NOT NULL,
FECHA_INICIAL DATE NOT NULL,
FECHA_FINAL DATE,
TIEMPO INT,
VALORTOTAL MONEY NOT NULL,
SALDO MONEY,
ABONO_INICIAL MONEY,
DEVUELTO BIT,
CONSTRAINT PK_IDALQUILER PRIMARY KEY(IDALQUILER),
CONSTRAINT FK_CARRO FOREIGN KEY (IDCARRO) REFERENCES CARRO(IDCARRO),
CONSTRAINT FK_CLIENTE FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE PAGOS(
IDPAGOS INT NOT NULL IDENTITY(1,1),
IDALQUILER INT NOT NULL,
FECHA DATE NOT NULL,
VALOR MONEY NOT NULL,
CONSTRAINT PK_IDPAGOS PRIMARY KEY(IDPAGOS),
CONSTRAINT FK_IDALQUILER FOREIGN KEY(IDALQUILER) REFERENCES ALQUILER(IDALQUILER)
);

-- 1.1 ejecutado
-- 1.2. cuanatos alquileres ha tenido un carro espcifico desde una fecha especifica
DECLARE @IDCARRO INT;
DECLARE @FECHA DATE;
SELECT * FROM ALQUILER WHERE IDCARRO=@IDCARRO AND FECHA=@FECHA;
--1.3. El Total de saldo en un dia especifico
SELECT SUM(SALDO) FROM  ALQUILER WHERE FECHA=@FECHA;
--1.4. realizar consulta
SELECT 
CL.CEDULA,
CL.NOMBRE,
AL.FECHA,
AL.SALDO,
CR.PLACA,
CR.MARCA
FROM 
CLIENTE AS CL 
LEFT JOIN 
ALQUILER AS AL ON CL.IDCLIENTE=AL.IDCLIENTE
 JOIN CARRO AS CR ON CR.IDCARRO=AL.IDCARRO
--1.5. Los clientes que no han alquilado en un periodo especifico
SELECT * FROM CLIENTE AS CL
INNER JOIN ALQUILER AS AL
ON AL.DEVUELTO=0 AND AL.FECHA!=NULL
--1.6 realice la siguiente consulta desde una fecha especifica
SELECT * 
FROM ALQUILER AS A
INNER JOIN PAGOS AS P ON
COUNT(IDPAGOS)=P.VALOR
--1.7. una Consulta asi: consolidado por carros en un periodo especifico
SELECT * FROM CARRO AS C
INNER JOIN ALQUILER AS A ON
SUM(A.IDALQUILER)=0
--1.8. el primer alquiler de un cliente
SELECT * FROM ALQUILER AS A
--2.1. realice una vista que muestre la informacion del punto 1.4
-- REALIZADO
--2.2. realice un filtro por fecha inicial de alquiler